"""Add mac_vendor fields and asset_services table

Revision ID: 97af5de1cc55
Revises: 
Create Date: 2026-01-26 20:17:27.340754

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '97af5de1cc55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use ADD COLUMN IF NOT EXISTS — safe to run on a DB created via create_all
    op.execute("ALTER TABLE scan_assets ADD COLUMN IF NOT EXISTS mac_vendor VARCHAR")
    op.execute("ALTER TABLE scan_assets ADD COLUMN IF NOT EXISTS os_family VARCHAR")
    op.execute("ALTER TABLE scan_assets ADD COLUMN IF NOT EXISTS os_accuracy INTEGER")
    op.execute("ALTER TABLE scan_assets ADD COLUMN IF NOT EXISTS uptime VARCHAR")
    op.execute("ALTER TABLE scan_assets ADD COLUMN IF NOT EXISTS first_seen TIMESTAMP")
    op.execute("ALTER TABLE scan_assets ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_assets', 'last_seen')
    op.drop_column('scan_assets', 'first_seen')
    op.drop_column('scan_assets', 'uptime')
    op.drop_column('scan_assets', 'os_accuracy')
    op.drop_column('scan_assets', 'os_family')
    op.drop_column('scan_assets', 'mac_vendor')
    # ### end Alembic commands ###
